### PR TITLE
Nuv scan

### PR DESCRIPTION
**Pull request by giusdp**
I'm opening this PR as draft to keep track of the progress and discussion around nuv scan (it will also cover #8). 
The README has some design on the scan subcommand.

I threw together a simple plan of action so it's open for discussion on what to do:

The steps to implement a pipeline for scanning a project and generating a Taskfile I imagined:

- [x] Check if "packages" folder is present in current directory or given path
 - - [x] If not present: give feedback to user and stop here
- [x] Scan inside the packages folder
- [x] Build a tree data structure:
 - root node (first level) is packages folder
 - second level nodes can be: folders = openwhisk packages, files = openwhisk actions (of default ow package)
 - third level nodes can be: files = openwhisk actions, folders = multifile openwhisk actions
- [x] Parse the tree & gen a DS of Task commands based on type of node
- - [x] packages commands
- - [x] single file action commands
- - [x] multi file action commands
- [x] Merge together the task commands into a taskfile

This is basically thinking out loud so I'd like to polish it and understand better how nuv scan would work.

Also, I added [testify](github.com/stretchr/testify) to use in tests.

### CODE REVIEW

**Comment by msciabarra** [comment]
I would make tests simpler :)

**Comment by msciabarra** [comment]
I reviewer the PR and it relies on the afero library that is a virtual filesystem library. I admit it is a fascinating library and open positive scenarios that could be the ability to deploy over http. However after careful thinking I have to rejec the usage on the basis of 3 reasons:

- first, the most important, nuv tool should work on different operating systems running different filesystems, so we will have to test against extfs, ntfs, hfps. Those have different semantics, for example the first is case sensitive, the second case insesntive and the third case preserving, not to talk of permissions I had significative problems in another project for this reasons. If we test against a virtual filesystem we miss all those potential bugs
- I do not want to rely on a third part library for things as basic as filessyte acces. I want we use os.Mkdir, not affero.Mkdir, as the standard library is going to be more supprted that third part libraries.
- resulting tests are pretty complex, as you have to write a lot of code to create various component. I understand it is ejoyable as go coding exercise but it is a nightmare for maintenance, if we have to test a deployment, let's include a test deployment in code. For example openwhisk has horrible tests written in scala with emedded code for testing. They are a nightmare to runs. So I do not want the test artifacts to be embedded in the tests. The should be separate and not build on the fly in the virtual filesystem

**Comment by msciabarra** [comment]
I know giudsp, I added the motivations here - we do not want to say "no" without a valid reason. Our main concern is testing again real filesytems

**Comment by sciabarracom** [comment]
Code looks fine but I need a "simple" integration test

Can you create a simple folder tests in the top level and add below a sample project with the folder and subfolders?

Ideally running `nuv scan` it should generate a `nuvolaris.yml` in the top level.

Leave a `nuvolaris.yml.ok` to compare with, so we can implement in .githhub actions a simple Taskfile for tests as follows

```
  tests:
      dir: tests
      cmds:
         - nuv scan
         - diff nuvolaris.yml nuvoloaris.yml.ok
 ```

**Comment by msciabarra** [comment]
Looks fine to me - I leave it however umberged as it is scheduled for next milestone and Irina so Irina can work on the `nuv setup` command that we relase first.

**Review by irinacodes — APPROVED** [review]

**Pull request merged**
